=== FD-XML-2025/BasicCombatGame/BeatThemUp/Content/xsd/credits.xsd
<?xml version="1.0"?>
<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:yr="http://www.yakuzasrevenge/credits"
        targetNamespace="http://www.yakuzasrevenge/credits"
        elementFormDefault="qualified">

    <element name="credits" type="yr:Credits"/>

    <!-- Root Content -->
    <complexType name="Credits">
        <sequence>
            <element name="credit" type="yr:Credit" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- A credit is composed of a name and URL for the dev portfolio -->
    <complexType name="Credit">
        <sequence>
            <element name="name" type="string"/>
            <element name="url" type="anyURI"/>
        </sequence>
    </complexType>
</schema>

=== FD-XML-2025/BasicCombatGame/BeatThemUp/Content/xml/credits.xml
<?xml version="1.0" encoding="UTF-8"?>
<credits
        xmlns='http://www.yakuzasrevenge/credits'
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation='http://www.yakuzasrevenge/credits credits.xsd'>
    
    <credit>
        <name>Valentin Chene</name>
        <url>https://github.com/Sarbatore</url>
    </credit>
    <credit>
        <name>Adam Nedic</name>
        <url>https://github.com/Anedi1</url>
    </credit>
    <credit>
        <name>Minh Huy Nguyen</name>
        <url>https://github.com/minhhuy20916</url>
    </credit>
    <credit>
        <name>Nguyen Phuoc Loc Luu</name>
        <url>https://github.com/luunpl</url>
    </credit>
</credits>
